# Generated by Django 3.1.6 on 2021-04-08 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='medical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_med', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=250)),
                ('contact', models.BigIntegerField()),
                ('reg_num', models.IntegerField()),
                ('est', models.IntegerField()),
            ],
        ),
    ]
