# Generated by Django 3.1.6 on 2021-05-02 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0002_medical_med_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medical',
            old_name='med_user',
            new_name='user',
        ),
    ]
