# Generated by Django 3.1.6 on 2021-05-05 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0009_medstocks_price'),
        ('User_app', '0002_ordersinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersinfo',
            name='med',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='medical.medical'),
        ),
    ]
