# Generated by Django 3.1.6 on 2021-05-05 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0003_ordersinfo_med'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='address',
            field=models.TextField(default=False, max_length=200),
        ),
    ]
